Vagrant.configure("2") do |config|

  # Base box
  config.vm.box = "ubuntu/jammy64"

  nodes = {
    "controller-1" => "192.168.56.10",
    "worker-1"     => "192.168.56.11"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024   # optimized for your 8GB RAM
        vb.cpus = 1
      end

      # Run common setup script
      node.vm.provision "shell", path: "scripts/common.sh"
    end
  end

end